#!/bin/bash
set -e
ROOTDIR=$(dirname "$(realpath "$0")")
cd "$ROOTDIR"

if [ ! -d "libs" ]; then
    mkdir libs
fi

if [ ! -d "debs" ];  then
    mkdir debs
fi

SOURCE="https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"
# Use the source below if you feel slow, or change it on your own.
SOURCE2="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/"

LIBC_PREFIX="libc6_"
LIBC_DBG_PREFIX="libc6-dbg_"

die() {
  echo >&2 "$1"
  exit 1
}

usage() {
  echo >&2 "Usage: $0 [-a] id"
  echo >&2 "Options: -o,--origin  fetch deb from ubuntu.com"
  exit 2
}

download_single() {
  local id=$1
  local deb_name=$LIBC_PREFIX$id.deb
  local dbg_name=$LIBC_DBG_PREFIX$id.deb
  echo "Getting $id"
  if [ -d "libs/$id" ]; then
    die "  --> Downloaded before. Remove it to download again."
  fi

  # download binary package
  local url="$SOURCE/$deb_name"
  echo "  -> Location: $url"
  echo "  -> Downloading libc binary package"
  wget "$url" 2>/dev/null -O debs/"$deb_name" || die "Failed to download package from $url"
  echo "  -> Extracting libc binary package"

  mkdir libs/"$id"
  ./extract debs/"$deb_name" libs/"$id"
  echo "  -> Package saved to libs/$id"

  # download debug info package
  local url="$SOURCE/$dbg_name"
  echo "  -> Location: $url"
  echo "  -> Downloading libc debug package"
  wget "$url" 2>/dev/null -O debs/"$dbg_name" || die "Failed to download package from $url"
  echo "  -> Extracting libc debug package"

  mkdir libs/"$id"/.debug
  ./extract debs/"$dbg_name" libs/"$id"/.debug
  echo "  -> Package saved to libs/$id/.debug"
}

if [[ $# -lt 1 ]]; then
  usage
fi

# Process all arguments
while [[ $# -gt 1 ]]; do
  case "$1" in
    -o|--origin)
      SOURCE="$SOURCE2"
      shift 1
      ;;
    *)
      echo >&2 "Unknown option: $1"
      exit 1
      ;;
  esac
done

download_single "$1"
